#!/bin/sh
#
# This script compiles and links and the binary
# We do some elf parsing here because we need to know the 
# hyplet size in advance.
sudo kpartx -a /opt/truly/linaro_fvp/armv8.img
#
GCC=gcc-linaro-4.9-2015.05-x86_64_aarch64-linux-gnu
CC=/opt/${GCC}/bin/aarch64-linux-gnu-gcc 
#READELF=/opt/${GCC}/bin/aarch64-linux-gnu-readelf
#OBJDUMP=/opt/${GCC}/bin/aarch64-linux-gnu-objdump

# simple isr hyplet
$CC   -I ../../../../include simple_hyplet.c hyplet_utils.c -o simple_hyplet
$CC   -I ../../../../include offlet_hyplet.c hyplet_utils.c -o offlethyplet


sudo mount /dev/mapper/loop0p2 /media/fvp
sudo cp offlethyplet /media/fvp//home/root/
sudo umount /media/fvp
