#!/bin/sh
#
# This script compiles and links and the binary
# We do some elf parsing here because we need to know the 
# hyplet size in advance.
sudo kpartx -a /opt/truly/linaro_fvp/armv8.img
#
GCC=gcc-linaro-4.9-2015.05-x86_64_aarch64-linux-gnu
CC=/opt/${GCC}/bin/aarch64-linux-gnu-gcc 
#READELF=/opt/${GCC}/bin/aarch64-linux-gnu-readelf
#OBJDUMP=/opt/${GCC}/bin/aarch64-linux-gnu-objdump

# simple isr hyplet
$CC   -I ../../../../include simple_hyplet.c hyplet_utils.c -o simple_hyplet
#$CC   -I ../../../../../include fault_hyplet.c hyplet_utils.c -o fault_hyplet

# timer usr hyplet
#$CC   -pthread -I ../../../../../include   -c test_isr_hyplet.c
#$CC   -pthread -I ../../../../../include  -c  hyplet_utils.c 
#$CC   -pthread -I ../../../../../include   -c main_test_hyplet.c
#$CC   -pthread main_test_hyplet.o test_isr_hyplet.o hyplet_utils.o -o  test_hyplet


sudo mount /dev/mapper/loop0p2 /media/fvp
sudo cp simple_hyplet /media/fvp//home/root/
#sudo cp test_hyplet /media/fvp/home/root/
#sudo cp rpcsender /media/fvp/home/root/ 
#sudo cp rpcrecv /media/fvp/home/root/
#sudo cp hyp_perf_test /media/fvp/home/root/
#sudo umount /media/fvp
